name: Auto Sync to GitLab

on:
  push: 
    branches: [ main ]
  schedule: 
    - cron: '0 1 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "actions@github.com"
      - name: Push to GitLab
        run: |
          git remote add gitlab http://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@firestones.org:8069/onapc/SukiUI.git
          git push --force gitlab main
